esphome:
  name: my-rtsp-test-esp32-cam
  friendly_name: My RTSP Test ESP32 Cam
  includes: micro_rtsp

external_components:
  - source: components

esp32:
  board: esp32dev
  framework:
    type: arduino

psram:
  mode: octal
  speed: 80MHz

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "01234567890123456789012345678901234567890123"

ota:
  - platform: esphome
    password: "01234567890123456789012345678901"

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.100.10
    gateway: 192.168.100.254
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "My-Rtsp-Test-Esp32-Cam"
    password: "012345678901"

captive_portal:

esp32cam_rtsp_server:
  # Uncomment the following settings to set specific values.
  # camera: esp32cam_aithinker
  # external_clock_frequency: 16000000
  # max_framerate: 5 fps
  # port: 554
  resolution: UXGA
  # brightness: 0
  # contrast: 0
  # saturation: 0
  # special_effect: none
  # white_balance: true
  # awb_gain: true
  # exposure_control: true
  # aec2: true
  # ae_level: 0
  # aec_value: 300
  # gain_control: false
  # agc_gain: 6
  # gain_ceiling: 2x
  # bpc: false
  # wpc: true
  # raw_gma: true
  horizontal_mirror: true
  vertical_flip: true
  # lenc: true
  # dcw: true
